version: "3.3"
services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_secret
      - POSTGRES_USER=usr
      - POSTGRES_DB=photos_website
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - db_secret
    
  photos-website:
    image: photos-website:latest
    ports: 
      - 80:80
    depends_on:
      - "postgres"

volumes:
  postgres_data:
secrets:
  db_secret:
    external: true
